var modules =
[
    [ "Return Codes", "group___c_r_d_s_y_n_c___return___codes.html", null ],
    [ "Synchronous Card Types", "group___c_r_d_s_y_n_c___card___types.html", null ],
    [ "General topics", "group___a_d_k___g_e_n_e_r_a_l.html", "group___a_d_k___g_e_n_e_r_a_l" ],
    [ "Initialization", "group___a_d_k___i_n_i_t_i_a_l_i_z_a_t_i_o_n.html", "group___a_d_k___i_n_i_t_i_a_l_i_z_a_t_i_o_n" ],
    [ "Configuration", "group___a_d_k___c_o_n_f_i_g_u_r_a_t_i_o_n.html", "group___a_d_k___c_o_n_f_i_g_u_r_a_t_i_o_n" ],
    [ "Transaction execution", "group___a_d_k___t_r_x___e_x_e_c.html", "group___a_d_k___t_r_x___e_x_e_c" ],
    [ "ICC Interface", "group___a_d_k___i_c_c___i_f.html", "group___a_d_k___i_c_c___i_f" ],
    [ "LED control", "group___a_d_k___l_e_d.html", "group___a_d_k___l_e_d" ],
    [ "Import/Export Utility", "group__inf__util.html", "group__inf__util" ],
    [ "Property Database API", "group__propdb.html", "group__propdb" ],
    [ "Multi Application Controller functions", "group__mac.html", "group__mac" ],
    [ "Error codes", "group___m_s_r___e_r_r_o_r___c_o_d_e_s.html", "group___m_s_r___e_r_r_o_r___c_o_d_e_s" ],
    [ "Status code", "group___m_s_r___s_t_a_t_u_s___c_o_d_e_s.html", "group___m_s_r___s_t_a_t_u_s___c_o_d_e_s" ],
    [ "Card Type Code", "group___m_s_r___c_a_r_d___c_o_d_e_s.html", "group___m_s_r___c_a_r_d___c_o_d_e_s" ],
    [ "Track Type Code", "group___m_s_r___t_r_a_c_k___t_y_p_e_s.html", "group___m_s_r___t_r_a_c_k___t_y_p_e_s" ],
    [ "Options bitmask", "group___m_s_r___o_p_t_i_o_n_s___b_i_t_m_a_s_k.html", "group___m_s_r___o_p_t_i_o_n_s___b_i_t_m_a_s_k" ],
    [ "LED states", "group___l_e_d___s_t_a_t_e_s.html", "group___l_e_d___s_t_a_t_e_s" ],
    [ "management functions", "group___power.html", "group___power" ],
    [ "Dialog invocation return values", "group___d_e_f___l_i_b_s_d_i_c_l_i_e_n_t___d_i_a_l_o_g___r_e_t_u_r_n___v_a_l_u_e_s.html", "group___d_e_f___l_i_b_s_d_i_c_l_i_e_n_t___d_i_a_l_o_g___r_e_t_u_r_n___v_a_l_u_e_s" ],
    [ "Dialog options", "group___d_e_f___l_i_b_s_d_i_c_l_i_e_n_t___d_i_a_l_o_g___o_p_t_i_o_n_s.html", "group___d_e_f___l_i_b_s_d_i_c_l_i_e_n_t___d_i_a_l_o_g___o_p_t_i_o_n_s" ],
    [ "Menu options", "group___d_e_f___l_i_b_s_d_i_c_l_i_e_n_t___m_e_n_u___o_p_t_i_o_n_s.html", "group___d_e_f___l_i_b_s_d_i_c_l_i_e_n_t___m_e_n_u___o_p_t_i_o_n_s" ],
    [ "SDI Protocol Error Codes", "group___s_d_i___p_r_o_t_o_c_o_l___e_r_r_o_r___c_o_d_e_s.html", "group___s_d_i___p_r_o_t_o_c_o_l___e_r_r_o_r___c_o_d_e_s" ],
    [ "SDI Protocol Initialization Options", "group___s_d_i___p_r_o_t_o_c_o_l___i_n_i_t___o_p_t_i_o_n_s.html", "group___s_d_i___p_r_o_t_o_c_o_l___i_n_i_t___o_p_t_i_o_n_s" ],
    [ "System LED functions", "group__led.html", "group__led" ],
    [ "Netloader", "group__netloader.html", "group__netloader" ],
    [ "System statusbar functions", "group__sysbar.html", "group__sysbar" ],
    [ "Low level system power management functions. Please use vfisyspm.h instead.", "group__syspm.html", "group__syspm" ],
    [ "System beep functions", "group__sysbeep.html", "group__sysbeep" ],
    [ "System property functions", "group__syserro.html", "group__syserro" ],
    [ "System property functions", "group__sysinfo.html", "group__sysinfo" ],
    [ "installation functions", "group__vfisysinstall.html", "group__vfisysinstall" ],
    [ "Utility functions", "group__util.html", "group__util" ],
    [ "zontalk protocal APIs", "group__zontalk.html", "group__zontalk" ],
    [ "PED return codes", "group___p_e_d___r_e_t_u_r_n___c_o_d_e_s.html", "group___p_e_d___r_e_t_u_r_n___c_o_d_e_s" ],
    [ "PED status codes", "group___p_e_d___s_t_a_t_u_s___c_o_d_e_s.html", "group___p_e_d___s_t_a_t_u_s___c_o_d_e_s" ],
    [ "Notification callback types", "group___t_e_c___n_o_t_i_f_i_c_a_t_i_o_n___c_b_k___t_y_p_e.html", "group___t_e_c___n_o_t_i_f_i_c_a_t_i_o_n___c_b_k___t_y_p_e" ],
    [ "TEC technology code", "group___t_e_c___t_e_c_h_n_o_l_o_g_i_e_s.html", "group___t_e_c___t_e_c_h_n_o_l_o_g_i_e_s" ],
    [ "TEC return codes", "group___t_e_c___r_e_t_u_r_n___c_o_d_e_s.html", "group___t_e_c___r_e_t_u_r_n___c_o_d_e_s" ],
    [ "TEC start options", "group___t_e_c___s_t_a_r_t___o_p_t_i_o_n_s.html", "group___t_e_c___s_t_a_r_t___o_p_t_i_o_n_s" ],
    [ "TEC result data tags", "group___t_e_c___d_a_t_a___t_a_g_s.html", "group___t_e_c___d_a_t_a___t_a_g_s" ],
    [ "TEC option tags", "group___t_e_c___o_p_t_i_o_n___t_a_g_s.html", "group___t_e_c___o_p_t_i_o_n___t_a_g_s" ],
    [ "Graphical User Interface", "group__vfigui.html", "group__vfigui" ],
    [ "Printing functions", "group__vfiprt.html", "group__vfiprt" ],
    [ "inter process communication", "group__vfiipc.html", "group__vfiipc" ],
    [ "TLVLite", "group___t_l_v_lite.html", "group___t_l_v_lite" ],
    [ "SDI client setup", "group__sdisetup.html", "group__sdisetup" ],
    [ "Low level message interface", "group__sdilowlevel.html", "group__sdilowlevel" ],
    [ "System interface", "group__sdisystem.html", "group__sdisystem" ],
    [ "Display interface", "group__sdidisplay.html", "group__sdidisplay" ],
    [ "Printer interface", "group__sdiprinter.html", "group__sdiprinter" ],
    [ "MSR interface", "group__sdimsr.html", "group__sdimsr" ],
    [ "Card reader interface", "group__sdicrd.html", "group__sdicrd" ],
    [ "PIN entry interface", "group__sdiped.html", "group__sdiped" ],
    [ "Crypto interface", "group__sdisec.html", "group__sdisec" ],
    [ "Data interface", "group__sdidata.html", "group__sdidata" ],
    [ "VCL interface", "group__sdivcl.html", "group__sdivcl" ],
    [ "EMV contact interface", "group__sdiemvct.html", "group__sdiemvct" ],
    [ "EMV contactless interface", "group__sdiemvctls.html", "group__sdiemvctls" ],
    [ "SDI client NFC interface", "group__sdinfc.html", "group__sdinfc" ],
    [ "SDI client VAS interface", "group__sdivas.html", "group__sdivas" ],
    [ "SDI and EMV callbacks", "group__sdicallback.html", "group__sdicallback" ],
    [ "SDI plugin commands", "group__sdiplugin.html", "group__sdiplugin" ],
    [ "Com_verifone_seccmd", "group__com__verifone__seccmd.html", "group__com__verifone__seccmd" ],
    [ "Config", "group___config.html", "group___config" ],
    [ "Vss", "group__vss.html", "group__vss" ]
];